import {contentTree, copiedContent} from "../../types/pathHarvester.types";

/**
 * Represents the state of the process, including the structure of directories and files.
 *
 * @property {string} [sessionId] - An optional session identifier.
 * @property {string} directoryPath - The path of the directory being processed.
 * @property {OptionValue} [option] - The selected processing option.
 * @property {string} [message] - A message related to the process.
 * @property {Object} copiedContent - The structure and content that has been copied.
 * @property {string} copiedContent.folderStructure - A textual representation of the folder structure.
 * @property {string} copiedContent.ignoredFiles - A list of ignored files as a string.
 * @property {contentTree} [copiedContent.contentTree] - The hierarchical structure of processed files and directories.
 * @property {string} [gptAnswer] - A response generated by GPT (optional).
 */
export type StepState = {
  sessionId?: string;
  directoryPath: string;
  option?: OptionValue;
  message?: string;
  copiedContent: copiedContent;
  gptAnswer?: string;
};

// Other types remain unchanged
export type TableRow = string[];
export type gptChatTableSegment = { content: TableRow[] };
export type gptChatCodeSegment = { content: string };
export type ChatEntry = {
  role: 'user' | 'gpt';
  content: string;
};
export type OptionValue = '' | '1' | '2' | '3' | '4';
